name: orbital_cleanup
description: A space debris cleanup game
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.28.0
  audioplayers: ^5.2.1
  google_fonts: ^5.1.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/audio/
    - assets/fonts/
    
  # Required audio files:
  # - assets/audio/background_music.mp3
  # - assets/audio/collect.mp3
  # - assets/audio/explosion.mp3
  # - assets/audio/level_complete.mp3
  # - assets/audio/game_over.mp3
  # - assets/audio/button_click.mp3 